Custom pages for syntax highlighter
toolbox-team/reddit-moderator-toolbox pull request #394
Opened 2020-10-10 19:32 UTC by itskieranp

Resolves #92 

I was looking to see if this was possible myself, and found issue #92 via a [recent Reddit thread](https://www.reddit.com/r/toolbox/comments/go7cas/is_it_possible_to_add_other_wiki_pages_to_syntax/). Felt I was confident enough to take a look at the code, and as it doesn't appear that anybody is working on this, I gave it a go.

This allows the user to specify which wiki pages (besides the stylesheet as it's currently referenced with `/about/stylesheet` but not `/wiki/config/stylesheet` - let me know if you want that to be added as a checkbox toggle for consistency's sake and I'll probably handle both on the same checkbox), and the defaults are the current list of pages Toolbox supports: `config/automoderator`, `automoderator-schedule`, and `toolbox`, which can be removed if the user wishes to.

To account for people putting "json" instead of "javascript" as the language, that gets changed on-the-fly as the page loads, hopefully pre-empting the inevitable support requests. (And given I did that myself for a while until I realised the CodeMirror mode was called `javascript` not `json` - I know I'd be one of them)

Feel free to get in touch - I've joined the Discord and my PFP is the same as on here.

2020-10-10 20:02 UTC, creesch requested changes
> To account for people putting "json" instead of "javascript" as the language, that gets changed on-the-fly as the page loads, hopefully pre-empting the inevitable support requests. (And given I did that myself for a while until I realised the CodeMirror mode was called javascript not json - I know I'd be one of them)


I am fairly sure we should just put in json and not javascript. While the mode file for it is called 'javascript' it actually does some specific stuff for json, [see this](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/libs/codemirror/mode/javascript.js#L914) MIME type definition. 

It also looks like you refer to the language rather than the mime types like we did before. Additionally I am not sure how codemirror is going to handle faulty languages which currently you don't account for. 

The latter two can easily be accounted for by implementing a little switch statement when encountering a wiki page on line 195 doing something like this: 

```javascript
switch (wikiPages[onWikiPage]) {
  case 'css':
    wikiPages[onWikiPage] = 'text/css';
    break;
  case 'json':
    wikiPages[onWikiPage] = 'application/json';
    break;
  case 'markdown':
    wikiPages[onWikiPage] = 'text/markdown';
    break;
  case 'yaml':
    wikiPages[onWikiPage] = 'text/x-yaml';
    break;
  default:
    wikiPages[onWikiPage] = 'text/markdown';
}
```

2020-10-10 20:02 UTC, creesch commented on extension/data/modules/syntax.js
> +        if (onWikiPage) {
Why is this a second check and not simply included in the above bit?

2020-10-10 20:05 UTC, creesch commented on extension/data/modules/syntax.js
> +        for (const page in wikiPages) {
It is probably better to start by checking if we are on a wiki edit page to begin with.

2020-10-10 21:21 UTC, itskieranp commented
All the comments have been addressed. Thanks for the prompt feedback on this!

2020-10-10 21:26 UTC, creesch commented on extension/data/modules/syntax.js
> +                            wikiPages[page] = 'markdown';
Is this still supposed to be in here?

2020-10-10 21:28 UTC, itskieranp commented on extension/data/modules/syntax.js
> +                            wikiPages[page] = 'markdown';
The intention is to update the settings so that an invalid setting such as "dfugjhdkjghnk" gets changed to "markdown" in the UI, and I found when I was testing that modifying the settings object updates the settings that are displayed in the settings UI (and presumably stored in settings storage as well).

2020-10-10 21:34 UTC, creesch approved these changes

2020-10-11 03:26 UTC, Geo1088 requested changes
Good work so far! A couple thoughts from me.

2020-10-11 03:26 UTC, Geo1088 commented on extension/data/modules/syntax.js
> +        },
Should also contain `'config/stylesheet': 'css'` to CSS highlighting works on `/wiki/edit/config/styesheet` as well as `/about/stylesheet`

2020-10-11 03:26 UTC, Geo1088 commented on extension/data/modules/syntax.js
> +                if (Object.prototype.hasOwnProperty.call(wikiPages, page)) { // ESLint guard-for-in
Prefer `for...of` iterating over `Object.keys(obj)` or `Object.entries(obj)` instead of `for...in` with a guard. For example:

```js
for (const [page, language] of Object.entries(wikiPages)) {
	// ...
}
```

Or, even better, why not forgo the `for` loop altogether and get the name of the current page from the regexp at the beginning?

```js
// Are we on a wiki edit or create page?
const wikiMatch = location.pathname.match(/\/wiki\/(edit|create)\/([a-z0-9-_/]*[a-z0-9-_])/);
if (!wikiMatch) {
    return;
}

// Are we on a page from the list in the settings?
const page = wikiMatch[2];
if (!wikiPages[page]) {
    return;
}

// We now know the name of the current page and can start making the editor and looking up the mime type
```

2020-10-11 08:19 UTC, creesch commented on extension/data/modules/syntax.js
> +        },
@Geo1088 `/about/stylesheet` is handled else where and should not be included.

2020-10-11 08:38 UTC, Geo1088 commented on extension/data/modules/syntax.js
> +        },
I'm aware, the page under `/about` is handled manually since it's not technically a wiki edit page but a separate interface. The stylesheet can be edited in the normal wiki edit interface too, though, which is what I'm saying should be handled.

2020-10-11 08:39 UTC, itskieranp commented on extension/data/modules/syntax.js
> +        },
I didn't add it originally so as not to cause confusion if someone removed it - if we add that as a default, should we then detect if it's there before running on /about/stylesheet?

2020-10-11 08:42 UTC, creesch commented on extension/data/modules/syntax.js
> +        },
@itskieranp I'd say only the wiki page for it not the `about` one.

2020-10-11 08:43 UTC, Geo1088 commented on extension/data/modules/syntax.js
> +        },
Agreed, probably not worth it to add more custom logic there. Most people who don't want syntax highlighting on the stylesheet page will just turn the entire module off anyway.

2020-10-11 10:21 UTC, itskieranp commented
Alrighty, pushed some more commits addressing these requests.

2020-10-11 12:45 UTC, Geo1088 approved these changes
Nice, lgtm! Thanks for the PR~

2020-10-11 12:45 UTC, merged