Changes to the flair selector
toolbox-team/reddit-moderator-toolbox pull request #458
Opened 2021-02-24 00:39 UTC by Xeoth

Fixes #457. Besides that, adds colors to the dropdown to show how the templates will look on New Reddit.

2021-03-12 21:06 UTC, creesch commented
@Geo1088 you request review yourself, do you still want to look this over?

2021-03-12 22:00 UTC, Geo1088 commented
I planned to, but don't let me hold this back if you think it's good to go.

2021-03-13 23:08 UTC, Geo1088 requested changes
This PR has undesirable behavior when clicking into the flair tab, then out, then back in. The flair templates end up duplicated in the dropdown, and the values of the text boxes are also overwritten with the current value each time this happens. This is probably a result of the way the mod button's UI code has been structured for a long time, rather than being a result of your specific changes, but I think we should do something about that before we merge this.

![image](https://user-images.githubusercontent.com/4165301/111052185-efb25e80-8426-11eb-9f9e-a184bf230493.png)

Is it possible to move the setup code so it happens once, when the popup is first created, rather than only when the tab is entered? If not, we should at least store some indication that the tab has already been loaded and shouldn't be set up again.

2021-03-13 23:08 UTC, Geo1088 commented on extension/data/modules/modbutton.js
> +                    <p style="clear:both;" class="mod-popup-flair-input"><label for="flair-class" class="mod-popup-flair-label">Class:</label><input id="flair-class" class="flair-class tb-input" type
Style nit: I know you just moved these lines down, but could you clean them up so the elements aren't all strung together on one line?

2021-03-14 00:08 UTC, Geo1088 commented on extension/data/styles/toolbox.css
> +}
One more thing I forgot to mention: You should be able to use `vertical-align: baseline !important` to do this centering rather than relying on messy relative positioning. `.tb-action-button` gets `vertical-align: bottom !important` which you can override back to the default value.

2021-03-16 17:01 UTC, Xeoth commented
Thanks for the review, it should all be fixed now.

2021-03-16 19:28 UTC, Geo1088 commented on extension/data/styles/toolbox.css
> +    vertical-align: super !important;
Is this `super` instead of `baseline` intentionally? I haven't tried running this again, if it looks good to you then we can go with it.

2021-03-16 19:40 UTC, Geo1088 commented on extension/data/styles/toolbox.css
> +    vertical-align: super !important;
Weird issues with `baseline` discussed [in Discord](https://discord.com/channels/535490452066009090/535490452066009093/821466215381467146), using `super` is good enough for now and I'll plan to look over this more when I'm in the neighborhood with #459.

2021-03-16 19:40 UTC, Geo1088 approved these changes

2021-03-16 19:40 UTC, merged