Filter by usernote tag
toolbox-team/reddit-moderator-toolbox pull request #546
Opened 2021-12-11 19:41 UTC by dequeues

Implement #534 

There is now a dropdown on the usernote search page of all the user note titles, and "All" which you can filter the usertags with.
First PR here, please be kind. 👋

2021-12-14 19:48 UTC, eritbh requested changes
Hey, thanks so much for taking the time to write a PR for this! I just have a couple suggestions before we can merge it.

2021-12-14 19:48 UTC, eritbh commented on extension/data/modules/usernotes.js
> +                }).filter(user => user.notes.filter(notes => filterKey === 'all' || notes.type === filterKey).length > 0);
What you have here works perfectly fine, we can probably get better performance out of it by putting this in the existing `notes` filter that starts on line 1099. Something like this:

```js
const filteredData = allUsers.map(user => ({
    name: user.name,
    notes: user.notes.filter(note => {
        // Filter out notes not matching `contentText`
        if (!note.note.toLowerCase().includes(contentText.toLowerCase())) {
            return false;
        }

        // Filter out note types that are not `filterKey`
        if (filterKey !== 'all' && filterKey !== note.type) {
            return false;
        }

        return true;
    }),
})).filter(user => // ...
```

Doing all the filtering in the same `.filter` call means we don't need to iterate over all the users and notes multiple times, which for usernotes can be a big concern (some subreddits have a *lot* of usernotes). This new structure will be a little more flexible and allows us to filter on multiple different properties within a single loop.

This is very minor, but I also changed the iteration variable from `notes` to `note` - inside the loop, it refers to a single note object, not an array of them, so the singular name makes the code just a bit easier to read.

2021-12-14 19:48 UTC, eritbh commented on extension/data/modules/usernotes.js
> +                            ${colors.map(op => `<option value=${op.key}>${op.text}</option>`).join('')}
We unfortunately aren't super consistent about this in the rest of the code right now, but any time user input is put into HTML, it should be run through `TBHelpers.htmlEncode()` first.

```suggestion
                            ${colors.map(op => `<option value=${op.key}>${TBHelpers.htmlEncode(op.text)}</option>`).join('')}
```

2021-12-14 20:05 UTC, dequeues commented
Agree with both - I'll update the PR soon. Thanks.

2021-12-15 22:02 UTC, eritbh approved these changes

2021-12-15 22:15 UTC, eritbh commented
Thanks again for the contribution! This should land in our next feature update.

2021-12-15 22:15 UTC, merged