Implement colors for usernote tags
toolbox-team/reddit-moderator-toolbox pull request #560
Opened 2022-03-16 20:59 UTC by dequeues

Implement #550

2022-03-17 14:36 UTC, eritbh requested changes
Thanks for the PR! Just one suggestion.

2022-03-17 14:36 UTC, eritbh commented on extension/data/modules/usernotes.js
> +                                <span class="note-type" ${color.key !== 'none' ? `style="color:${color.color}"` : ''}>[${color.text}]</span>
I know we don't do this in any of the surrounding code right now, but let's HTML encode this value just to be safe:
```suggestion
                                <span class="note-type" ${color.key !== 'none' ? `style="color:${TBHelpers.htmlEncode(color.color)}"` : ''}>[${color.text}]</span>
```

2022-03-17 14:56 UTC, dequeues commented on extension/data/modules/usernotes.js
> +                                <span class="note-type" ${color.key !== 'none' ? `style="color:${color.color}"` : ''}>[${color.text}]</span>
Ah yes, I totally forgot about that. I'll update it soon

2022-03-17 15:43 UTC, creesch commented on extension/data/modules/usernotes.js
> +                                <span class="note-type" ${color.key !== 'none' ? `style="color:${color.color}"` : ''}>[${color.text}]</span>
Good call, though we don't need to worry about injection much here as the subreddit config already has been put through domPurify here: https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/tbcore.js#L1361

Still, if for some reason we find ourselves with html that is technically safe it could still mess up rendering.

2022-03-20 22:44 UTC, eritbh approved these changes

2022-03-26 20:51 UTC, merged