Update modqueue caching to work with storage api
toolbox-team/reddit-moderator-toolbox pull request #599
Opened 2022-08-24 19:25 UTC by creesch

2022-09-07 20:39 UTC, eritbh requested changes

2022-09-07 20:39 UTC, eritbh commented on extension/data/background/handlers/modqueue.js
> +}
Writing this as an async function rather than explicitly returning a `new Promise` makes it a bit simpler to understand at first glance.

```suggestion
async function setQueueCache (subreddit, cacheObject) {
    const result = await browser.storage.local.get({[MODQUEUE_CACHE_NAME]: {}});
    result[subreddit] = cacheObject;
    await browser.storage.local.set({
        [MODQUEUE_CACHE_NAME]: result,
    });
}
```

2022-09-07 20:39 UTC, eritbh commented on extension/data/background/handlers/modqueue.js
> +}
Similar to above, could be cleaner as an async function

```suggestion
async function getQueueCache (subreddit) {
    const result = await browser.storage.local.get({[MODQUEUE_CACHE_NAME]: {}});
    if (Object.prototype.hasOwnProperty.call(result[MODQUEUE_CACHE_NAME], subreddit)) {
        return result[MODQUEUE_CACHE_NAME][subreddit];
    }
    return {};
}
```

2022-09-07 20:39 UTC, eritbh commented on extension/data/background/handlers/modqueue.js
> +        if (Object.keys(subredditQueueCache).length) {
Changing this check from `if (subredditQueueCache)` to this keys check seems unnecessary. Can we have `getQueueCache` return `null` or `undefined` by default instead of an empty object and keep this check (and the same type of check done further down) simple?

2022-09-07 20:39 UTC, eritbh commented on extension/data/background/handlers/modqueue.js
> +    getQueueCache(subreddit).then(subredditQueueCache => {
Wrapping this whole section in a callback makes the diff really ugly; lots of whitespace changes masking what's really changing. This call could be refactored to use `async`/`await` instead to avoid the callback and keep the overall structure closer to what we already have.

2022-09-08 17:48 UTC, creesch commented
Resolved the comments and reworked a bit more to make use of async/await. 

Also fixed two things I did encounter: 
- `refreshActive` being written to an object that wouldn't be read anymore. 
- Edge case where `refreshActive` would remain active if the browser is closed at the right moment (or in the future when the manifest v3 worker times out). `refreshActive` is now also a timestamp and if it is older than the TTL for the cache we can assume something went wrong in a previous call.

2022-09-08 18:00 UTC, eritbh requested changes
Just to confirm, are the newly added debug logs left in this PR intentionally?

One more nit to address and then this looks good to me

2022-09-08 18:02 UTC, creesch commented
> Just to confirm, are the newly added debug logs left in this PR intentionally?

Yup, should help in the future if I ever need to mess with it as it was now a pain to debug at times.

2022-09-08 18:03 UTC, eritbh approved these changes

2022-09-08 18:03 UTC, merged