Fix broken modnote hyperlinks
toolbox-team/reddit-moderator-toolbox pull request #892
Opened 2024-02-22 21:53 UTC by jenbanim

Fixes #890 

I really hope I did this right lol

2024-02-23 09:19 UTC, eritbh requested changes
Hey, thanks so much for submitting a PR for this! Really appreciate upstreaming fixes like this.

You were definitely right to update names and comments for this change, but there's some specific terminology we use in the project that I'd like to use here to disambiguate things a little more:

- Let's use "submission" everywhere rather than "link". "Link" sometimes means "any submission" but other times means "a submission which is not a self/text post," so we avoid using it in code that's relevant to any submission.
- "Fullname" is used to disambiguate thing IDs which also include the thing type prefix (`t1_`, `t3_`, etc) - whereas "ID" can also refer to the form without the prefix, as used in post/comment URLs and also certain API calls. (Reddit itself is even inconsistent about this - not every `*_id` field returned by reddit's various APIs is a fullname...) So any variable which works with prefixed IDs should refer to them as "fullnames" rather than just "IDs" to signal that the prefix is present and may need to be stripped later.

I've left comments about specific changes I'd recommend - feel free to make these updates yourself, or just enable the "Allow maintainer changes" option at the bottom of the PR sidebar in Github and I'll tweak them myself and get this merged. Sorry for the nitpicks!

2024-02-23 09:19 UTC, eritbh commented on extension/data/modules/modnotes.js
> + * In-page cache of comment fullnames to the link ID of their submission.
```suggestion
 * In-page cache of comment fullnames to the fullnames of their submissions.
```

2024-02-23 09:19 UTC, eritbh commented on extension/data/modules/modnotes.js
> +const linkIDCache = Object.create(null);
`submissionFullnamesCache`

2024-02-23 09:19 UTC, eritbh commented on extension/data/modules/modnotes.js
> + * Gets the link ID of a comment's corresponding submission.
```suggestion
 * Gets the fullname of a comment's corresponding submission.
```

2024-02-23 09:19 UTC, eritbh commented on extension/data/modules/modnotes.js
> + * @returns {Promise<string>} ID of the comment's submission
```suggestion
 * @returns {Promise<string>} Fullname of the comment's submission
```

2024-02-23 09:19 UTC, eritbh commented on extension/data/modules/modnotes.js
> +export function getLinkID (commentFullname) {
Suggest renaming to `getSubmissionFullname`

2024-02-23 09:19 UTC, eritbh commented on extension/data/modules/modnotes.js
> +    // Fetch the link ID fresh
```suggestion
    // Fetch the submission fullname fresh
```

2024-02-23 09:19 UTC, eritbh commented on extension/data/modules/modnotes.js
> +    const linkIDPromise = TBApi.getInfo(commentFullname)
Suggest renaming to `submissionFullnamePromise`

2024-02-23 09:19 UTC, eritbh commented on extension/data/modules/modnotes.js
> +        const linkID = await getLinkID(itemFullname);
Suggest renaming to `submissionFullname` - this code only cares about the unprefixed ID, so the comment above is still correct, but this variable does store the prefixed form and we don't do do the prefix stripping until the next line

2024-02-23 18:49 UTC, jenbanim commented
No worries about nitpicking, I totally understand the value of consistent naming. I wish Reddit itself were this consistent (eg. "pinned" vs "stickied" posts). Unfortunately I wasn't able to hit the "allow maintainer changes" button since that feature [seems to be broken when you fork to an organization](https://github.com/orgs/community/discussions/5634) as I did, ah well, lessons learned

Thanks for bearing with me, I think this should be good to go now

2024-02-26 16:26 UTC, eritbh approved these changes
Thanks again!

2024-02-26 17:08 UTC, merged